NUM_DICE = 5
CATEGORIES = [
    "aces",
    "twos",
    "threes",
    "fours",
    "fives",
    "sixes",
    "chance",
    "three_of_a_kind",
    "four_of_a_kind",
    "full_house",
    "small_straight",
    "large_straight",
    "yahtzee",
]
MAXIMUM_SCORES = {
    "aces": 5,
    "twos": 10,
    "threes": 15,
    "fours": 20,
    "fives": 25,
    "sixes": 30,
    "chance": 30,
    "three_of_a_kind": 30,
    "four_of_a_kind": 30,
    "full_house": 28,
    "small_straight": 30,
    "large_straight": 40,
    "yahtzee": 50,
}

MAXIMUM_THEORETICAL_SCORE = sum(MAXIMUM_SCORES.values())
# The expected score of a random play agent was found by running 2,000,000 episodes
EXPECTED_RANDOM_PLAY_SCORE = 45.03

ACTIONS = [
    "roll_dice_1",
    "roll_dice_2",
    "roll_dice_3",
    "roll_dice_4",
    "roll_dice_5",
    "roll_dice_1_and_2",
    "roll_dice_1_and_3",
    "roll_dice_1_and_4",
    "roll_dice_1_and_5",
    "roll_dice_2_and_3",
    "roll_dice_2_and_4",
    "roll_dice_2_and_5",
    "roll_dice_3_and_4",
    "roll_dice_3_and_5",
    "roll_dice_4_and_5",
    "roll_dice_1_and_2_and_3",
    "roll_dice_1_and_2_and_4",
    "roll_dice_1_and_2_and_5",
    "roll_dice_1_and_3_and_4",
    "roll_dice_1_and_3_and_5",
    "roll_dice_1_and_4_and_5",
    "roll_dice_2_and_3_and_4",
    "roll_dice_2_and_3_and_5",
    "roll_dice_2_and_4_and_5",
    "roll_dice_3_and_4_and_5",
    "roll_dice_1_and_2_and_3_and_4",
    "roll_dice_1_and_2_and_3_and_5",
    "roll_dice_1_and_2_and_4_and_5",
    "roll_dice_1_and_3_and_4_and_5",
    "roll_dice_2_and_3_and_4_and_5",
    "roll_dice_1_and_2_and_3_and_4_and_5",
    "choose_aces",
    "choose_twos",
    "choose_threes",
    "choose_fours",
    "choose_fives",
    "choose_sixes",
    "choose_chance",
    "choose_three_of_a_kind",
    "choose_four_of_a_kind",
    "choose_full_house",
    "choose_small_straight",
    "choose_large_straight",
    "choose_yahtzee",
]
ACTION_SPACE = len(ACTIONS)
